spring.application.name=TuumBankMock

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tuum_bank}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

mybatis.configuration.map-underscore-to-camel-case=true

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

server.port=8080

app.rabbitmq.accounts.exchange=accounts.exchange
app.rabbitmq.balances.exchange=balances.exchange
app.rabbitmq.transactions.exchange=transactions.exchange

app.outbox.publisher.fixed-delay-ms=2000
app.outbox.publisher.batch-size=20