spring.application.name=TuumBankMock

spring.datasource.url=jdbc:postgresql://localhost:5432/tuum_bank
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

mybatis.configuration.map-underscore-to-camel-case=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

server.port=8080